### ISSUE TITLE
Cannot delete notebooks

### ISSUE THREAD

**Issue by gamseb** [MicroPad/Classic#1]
I absolutely love micropad. I cannot find anywhere where to else ask, so I will ask here:
**How do I delete empty notebooks, that I have created by mistake?**
Thank you in advance.
Gamseb

**Comment by NickGeek** [comment]
# [Current (v3)](https://web.getmicropad.com)
1. Open the notepad using the notepads menu (if it's not already open)
2. Press the "cog" by the name of the notepad in the sidebar 
![image](https://user-images.githubusercontent.com/3462055/45932860-4b7a9a00-bfd7-11e8-99c1-2a60972cf7ad.png)
3. Select "Delete Notepad" on this menu: 
![image](https://user-images.githubusercontent.com/3462055/45932873-7d8bfc00-bfd7-11e8-80b4-e45e72ae5a61.png)

# [Classic (v1/v2)](https://getmicropad.com/web)
Go to the notepads dropdown 
![image](https://user-images.githubusercontent.com/3462055/45932812-613b8f80-bfd6-11e8-8df9-77bcde230aa2.png) and select the notepad you want to delete.

Then press the three bars on the header of the app and you should see this menu:
![image](https://user-images.githubusercontent.com/3462055/45932839-c8f1da80-bfd6-11e8-88f9-916a1cd08771.png)

**Comment by gamseb** [comment]
**Thank you!** 
Turns out my screen resolution didn't let me see the cog when the name was too long. 
The solution is to scroll to the end of the window.
I really appreciate your help.
Cheers
Gamseb

**Comment by NickGeek** [comment]
Great, no problem. For future reference, the place to ask questions about the web version of MicroPad would be https://github.com/MicroPad/Web
